### ISSUE TITLE
bioenv fails on metadata with 0 variance

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-diversity#56] opened 2016-10-27 18:43 UTC
See [this forum discussion](https://forum.qiime2.org/t/diversity-bioenv-column-s-in-the-data-frame-could-not-be-scaled/58/2) to see an example error and more details.

If the metadata map contains any columns with 0 variance, `bioenv` fails.

@gregcaporaso  suggests: 
`What we should probably do is detect these columns, not include them in the analysis, and print a warning in the resulting visualization about columns that were excluded, similar to what we do in the other visualizations in this plugin`

It could be useful to specify categories as an optional parameter to `bioenv`, e.g., to reduce runtime on very large metadata maps (such as from `qiita`) and/or to avoid certain categories.

**Comment by ebolyen** [comment] 2018-09-04 19:30
It looks like this is still possible because [this line](https://github.com/qiime2/q2-diversity/blob/cdcf24c551a8ca4246dce658fd6b608b174e224d/q2_diversity/_beta/_visualizer.py#L50) will strip samples making it possible for 0 variance to occur again.

If that filtering happened at the top, then I think everything would work as expected.

Discovered in the process of debugging [this forum issue](https://forum.qiime2.org/t/scaling-error-while-running-bioenv/5648/4).

**Comment by ChrisKeefe** [comment] 2020-06-17 17:32
I'm inclined to mark this a duplicate of #275 and close.

The two issues describe the same problem, @Oddant1's description is overall more comprehensive/approachable, and closing this issue will replace one complex issue with multiple simpler issues that already exist. (i.e. this re-opened issue is also arguably a duplicate of #73).

Other opinions, anyone?

**Comment by thermokarst** [comment] 2020-06-17 18:02
Yeah, I agree, we should close this, since @Oddant1's issue in #275 is more comprehensive (even though #275 is a duplicate of this issue).

> this re-opened issue is also arguably a duplicate of #73

I'm not so sure about that - #73 is a feature request that came up here as a "nice-to-have," but is unrelated to the bug that prompted Evan to re-open this issue.

**Closed by thermokarst** 2020-06-17 18:02 UTC
