### ISSUE TITLE
improve error message in --p-pairwise comparisons 

### ISSUE THREAD

**Issue by antgonza** [qiime2/q2-diversity#150] opened 2017-10-03 14:43 UTC
If a metadata column has 1 group with 1 sample, the error displayed is:
```bash
Plugin error from diversity:

  All values in the grouping vector are unique. This method cannot
  operate on a grouping vector with only unique values (e.g., there are
  no 'within' distances because each group of objects contains only a
  single object).

Debug info has been saved to /var/folders/17/c40mmrx56w918s7lp6ds2jvw0000gq/T/qiime2-q2cli-err-prbsm9i6.log
```
and the log:
```python
Traceback (most recent call last):
  File "/Users/antoniog/miniconda3/envs/qiime2-2017.9/lib/python3.5/site-packages/q2cli/commands.py", line 218, in __call__
    results = action(**arguments)
  File "<decorator-gen-283>", line 2, in beta_group_significance
  File "/Users/antoniog/miniconda3/envs/qiime2-2017.9/lib/python3.5/site-packages/qiime2/sdk/action.py", line 201, in callable_wrapper
    output_types, provenance)
  File "/Users/antoniog/miniconda3/envs/qiime2-2017.9/lib/python3.5/site-packages/qiime2/sdk/action.py", line 393, in _callable_executor_
    ret_val = callable(output_dir=temp_dir, **view_args)
  File "/Users/antoniog/miniconda3/envs/qiime2-2017.9/lib/python3.5/site-packages/q2_diversity/_beta/_visualizer.py", line 193, in beta_group_significance
    permutations=permutations)
  File "/Users/antoniog/miniconda3/envs/qiime2-2017.9/lib/python3.5/site-packages/q2_diversity/_beta/_visualizer.py", line 110, in _get_pairwise_group_significance_stats
    permutations=permutations)
  File "/Users/antoniog/miniconda3/envs/qiime2-2017.9/lib/python3.5/site-packages/skbio/stats/distance/_permanova.py", line 93, in permanova
    distance_matrix, grouping, column)
  File "/Users/antoniog/miniconda3/envs/qiime2-2017.9/lib/python3.5/site-packages/skbio/stats/distance/_base.py", line 1024, in _preprocess_input
    "All values in the grouping vector are unique. This method cannot "
ValueError: All values in the grouping vector are unique. This method cannot operate on a grouping vector with only unique values (e.g., there are no 'within' distances because each group of objects contains only a single object).
```

Even with all this info, it's not clear that the problem is that there is 1 group with 1 sample. Additionally, it will be good to know which are the problematic groups.

**Comment by jairideout** [comment] 2017-10-03 22:39
The error message is saying that there are no groups within the metadata column, every value is unique. Listing the problematic groups won't help users, because every "group" having `n=1` is the problem. Do you have suggestions for improving the error message?

**Comment by antgonza** [comment] 2017-10-03 23:02
An example of the problem I had is: in category "phenotype" we have 3 groups: "treatment" (n = 10), "control" (n =12) and "blank" (n=1). So my suggestion is that the output says that group blank has only has one sample. Remember that in the command you actually pass "phenotype" so it's fine not to add it. BTW the solution to move forward, as you can imagine, was to filter the sample "blank".

**Comment by jairideout** [comment] 2017-10-03 23:16
This error message shouldn't have been triggered in that case -- it's only intended to be triggered when *all* groups are `n=1`. So in your example, the `phenotype` column would need to have `treatment n=1`, `control n=1`, and `blank n=1` to trigger the error message.

Can you double-check the groups in your metadata column? And also consider that there may be samples in your metadata that aren't in your distance matrix, so those extra samples will be ignored.

**Comment by jairideout** [comment] 2017-10-10 18:34
@antgonza sent me some data to reproduce the issue. The error message is accurate, and it's occurring when pairwise tests are run (`--p-pairwise`). There were at least two "groups" of samples in @antgonza's metadata column that each contained only a single sample, which makes the error trigger as expected.

I can see this situation coming up frequently when running pairwise tests, and the error message isn't all that clear from a user's perspective. It may be useful to catch these errors when running pairwise tests and report that the tests couldn't be run for certain group pairs in the resulting visualization. That way users can still run pairwise tests without having to filter out those groups manually. @antgonza @gregcaporaso thoughts? If you guys like this plan, I'll create a new issue.

**Comment by antgonza** [comment] 2017-10-10 19:06
Thanks for clarifying the exact situation when this happens. I thought it was always in `beta-group-significance` but it only happens with `--p-pairwise`. I think your suggestion will work and the error could even have an example of the filtering `--p-where` parameter. 

I'm gonna rename this issue so it's more accurate.

**Comment by gregcaporaso** [comment] 2017-10-10 19:24
I like that plan @jairideout.

**Comment by jairideout** [comment] 2017-10-10 22:33
Great, thanks guys! Closing in favor of #155.

**Closed by jairideout** 2017-10-10 22:33 UTC
Labels: question
